// SPDX-License-Identifier: AGPL-3.0-or-later
//! Group conversations on top of the existing 1:1 channels.
//!
//! There is no server and no group key: a group is a **shared roster**, and a
//! group message is fanned out over the same end-to-end encrypted, onion-routed
//! session we already have with every member. Each hop is therefore exactly as
//! private as a direct message — nothing new to trust.
//!
//! What that buys us, and what it costs (documented in `docs/THREAT_MODEL.md`):
//!
//! * a member only receives what a sender could deliver — someone offline when
//!   the message is sent will not get it later (same limitation as 1:1),
//! * every member holds the same flat roster, so **any** member can rename the
//!   group or change its membership; there is no owner. Roster edits carry a
//!   version and the highest version wins, which converges but does not defend
//!   against a hostile member. Signed, ordered membership changes are the
//!   planned hardening.
//!
//! The roster travels as `GROUP_INFO` (see [`crate::envelope`]), which doubles
//! as the invitation: receiving one for an unknown group *is* being added.

use crate::error::GroupError;

/// One member of a group, as everyone in the group knows them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GroupMember {
    /// Ed25519 identity public key.
    pub identity: [u8; 32],
    /// Name to show; the member's own name wins once they send their profile.
    pub display_name: String,
    /// Onion address used to reach them.
    pub onion: String,
}

/// A group conversation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Group {
    /// Random 16-byte identifier, generated by whoever created the group.
    pub id: [u8; 16],
    /// Human-readable name.
    pub name: String,
    /// Roster version; bumped on every membership or name change.
    pub version: u32,
    /// When we first learned about the group (unix seconds).
    pub created_at: u64,
    /// Everyone in the group, including ourselves.
    pub members: Vec<GroupMember>,
}

impl Group {
    /// Start a new group. The creator is expected to be in `members`.
    pub fn create(name: &str, members: Vec<GroupMember>, now: u64) -> Result<Self, GroupError> {
        Ok(Self {
            id: new_group_id()?,
            name: name.trim().to_string(),
            version: 1,
            created_at: now,
            members,
        })
    }

    /// Whether `identity` is in the roster.
    pub fn has_member(&self, identity: &[u8; 32]) -> bool {
        self.members.iter().any(|m| &m.identity == identity)
    }

    /// Add a member and bump the version. Adding someone twice is a no-op.
    pub fn add_member(&mut self, member: GroupMember) -> bool {
        if self.has_member(&member.identity) {
            return false;
        }
        self.members.push(member);
        self.version = self.version.saturating_add(1);
        true
    }

    /// Remove a member and bump the version.
    pub fn remove_member(&mut self, identity: &[u8; 32]) -> bool {
        let before = self.members.len();
        self.members.retain(|m| &m.identity != identity);
        if self.members.len() == before {
            return false;
        }
        self.version = self.version.saturating_add(1);
        true
    }

    /// Rename and bump the version.
    pub fn rename(&mut self, name: &str) {
        self.name = name.trim().to_string();
        self.version = self.version.saturating_add(1);
    }

    /// Merge a roster received from another member.
    ///
    /// Newer version wins; an equal or older one is ignored, so two members
    /// echoing the same roster back and forth converge instead of looping.
    /// Returns `true` when anything changed.
    pub fn merge(&mut self, incoming: &Group) -> bool {
        if incoming.id != self.id || incoming.version <= self.version {
            return false;
        }
        self.name = incoming.name.clone();
        self.version = incoming.version;
        self.members = incoming.members.clone();
        true
    }
}

/// A fresh random group id.
pub fn new_group_id() -> Result<[u8; 16], GroupError> {
    let mut id = [0u8; 16];
    getrandom::getrandom(&mut id).map_err(|_| GroupError::Rng)?;
    Ok(id)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn member(n: u8, name: &str) -> GroupMember {
        GroupMember {
            identity: [n; 32],
            display_name: name.to_string(),
            onion: format!("{name}.onion"),
        }
    }

    #[test]
    fn ids_are_unique() {
        assert_ne!(new_group_id().unwrap(), new_group_id().unwrap());
    }

    #[test]
    fn create_starts_at_version_one() {
        let g = Group::create("Rodina", vec![member(1, "a"), member(2, "b")], 100).unwrap();
        assert_eq!(g.version, 1);
        assert_eq!(g.members.len(), 2);
        assert!(g.has_member(&[1; 32]));
    }

    #[test]
    fn membership_changes_bump_the_version() {
        let mut g = Group::create("Rodina", vec![member(1, "a")], 100).unwrap();
        assert!(g.add_member(member(2, "b")));
        assert_eq!(g.version, 2);
        // Adding the same identity again changes nothing.
        assert!(!g.add_member(member(2, "b")));
        assert_eq!(g.version, 2);
        assert!(g.remove_member(&[2; 32]));
        assert_eq!(g.version, 3);
        assert!(!g.remove_member(&[9; 32]));
        assert_eq!(g.version, 3);
    }

    #[test]
    fn newer_roster_wins_older_is_ignored() {
        let mut mine = Group::create("Rodina", vec![member(1, "a")], 100).unwrap();
        let mut theirs = mine.clone();
        theirs.add_member(member(2, "b")); // version 2

        assert!(mine.merge(&theirs));
        assert_eq!(mine.version, 2);
        assert!(mine.has_member(&[2; 32]));

        // Echoing the same roster back is not a change.
        assert!(!mine.merge(&theirs));

        // An older roster never wins.
        let mut stale = mine.clone();
        stale.version = 1;
        stale.members.clear();
        assert!(!mine.merge(&stale));
        assert_eq!(mine.members.len(), 2);
    }

    #[test]
    fn a_roster_for_another_group_is_refused() {
        let mut mine = Group::create("Rodina", vec![member(1, "a")], 100).unwrap();
        let mut other = Group::create("Práce", vec![member(3, "c")], 100).unwrap();
        other.version = 99;
        assert!(!mine.merge(&other));
        assert_eq!(mine.name, "Rodina");
    }
}
