// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/nullchat.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UmbraAppPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  UmbraApp
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    dynamic raw,
  );

  @protected
  UmbraApp
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    dynamic raw,
  );

  @protected
  UmbraApp
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    dynamic raw,
  );

  @protected
  RustStreamSink<NetEvent> dco_decode_StreamSink_net_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountView dco_decode_account_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ContactView dco_decode_contact_view(dynamic raw);

  @protected
  GifView dco_decode_gif_view(dynamic raw);

  @protected
  GroupMemberView dco_decode_group_member_view(dynamic raw);

  @protected
  GroupMessageView dco_decode_group_message_view(dynamic raw);

  @protected
  GroupView dco_decode_group_view(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountView> dco_decode_list_account_view(dynamic raw);

  @protected
  List<ContactView> dco_decode_list_contact_view(dynamic raw);

  @protected
  List<GifView> dco_decode_list_gif_view(dynamic raw);

  @protected
  List<GroupMemberView> dco_decode_list_group_member_view(dynamic raw);

  @protected
  List<GroupMessageView> dco_decode_list_group_message_view(dynamic raw);

  @protected
  List<GroupView> dco_decode_list_group_view(dynamic raw);

  @protected
  List<MediaItemView> dco_decode_list_media_item_view(dynamic raw);

  @protected
  List<MessageView> dco_decode_list_message_view(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SearchHitView> dco_decode_list_search_hit_view(dynamic raw);

  @protected
  MediaItemView dco_decode_media_item_view(dynamic raw);

  @protected
  MessageView dco_decode_message_view(dynamic raw);

  @protected
  NetEvent dco_decode_net_event(dynamic raw);

  @protected
  SearchHitView dco_decode_search_hit_view(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  UmbraApp
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    SseDeserializer deserializer,
  );

  @protected
  UmbraApp
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    SseDeserializer deserializer,
  );

  @protected
  UmbraApp
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NetEvent> sse_decode_StreamSink_net_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountView sse_decode_account_view(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ContactView sse_decode_contact_view(SseDeserializer deserializer);

  @protected
  GifView sse_decode_gif_view(SseDeserializer deserializer);

  @protected
  GroupMemberView sse_decode_group_member_view(SseDeserializer deserializer);

  @protected
  GroupMessageView sse_decode_group_message_view(SseDeserializer deserializer);

  @protected
  GroupView sse_decode_group_view(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountView> sse_decode_list_account_view(SseDeserializer deserializer);

  @protected
  List<ContactView> sse_decode_list_contact_view(SseDeserializer deserializer);

  @protected
  List<GifView> sse_decode_list_gif_view(SseDeserializer deserializer);

  @protected
  List<GroupMemberView> sse_decode_list_group_member_view(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupMessageView> sse_decode_list_group_message_view(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupView> sse_decode_list_group_view(SseDeserializer deserializer);

  @protected
  List<MediaItemView> sse_decode_list_media_item_view(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageView> sse_decode_list_message_view(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SearchHitView> sse_decode_list_search_hit_view(
    SseDeserializer deserializer,
  );

  @protected
  MediaItemView sse_decode_media_item_view(SseDeserializer deserializer);

  @protected
  MessageView sse_decode_message_view(SseDeserializer deserializer);

  @protected
  NetEvent sse_decode_net_event(SseDeserializer deserializer);

  @protected
  SearchHitView sse_decode_search_hit_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    UmbraApp self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    UmbraApp self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    UmbraApp self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_net_event_Sse(
    RustStreamSink<NetEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_view(AccountView self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_contact_view(ContactView self, SseSerializer serializer);

  @protected
  void sse_encode_gif_view(GifView self, SseSerializer serializer);

  @protected
  void sse_encode_group_member_view(
    GroupMemberView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_message_view(
    GroupMessageView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_view(GroupView self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_view(
    List<AccountView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_contact_view(
    List<ContactView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gif_view(List<GifView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_group_member_view(
    List<GroupMemberView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_message_view(
    List<GroupMessageView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_view(
    List<GroupView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_item_view(
    List<MediaItemView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_view(
    List<MessageView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_hit_view(
    List<SearchHitView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_item_view(MediaItemView self, SseSerializer serializer);

  @protected
  void sse_encode_message_view(MessageView self, SseSerializer serializer);

  @protected
  void sse_encode_net_event(NetEvent self, SseSerializer serializer);

  @protected
  void sse_encode_search_hit_view(SearchHitView self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUmbraApp(
    int ptr,
  );
}
