// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `broadcast_group_info`, `dial_once`, `duress_key`, `emit`, `flush_pending`, `gif_circuit`, `handle_payload`, `hex`, `hit_view`, `identity_pubkey`, `install_dir`, `kdf_line`, `log_line`, `now_secs`, `peer_tag`, `pending_count`, `pq_fingerprint_of`, `read_kdf`, `remember_group_routes`, `remember_peer`, `remember_pq_fingerprint`, `rt`, `safe_file_name`, `safe_gif_name`, `send_or_queue`, `send_profile`, `socks_port_now`, `spawn_keepalive`, `spawn_updater`, `unhex16`, `unhex`, `view_of`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Incoming`, `Inner`, `Pending`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`

/// Install the update the user was offered. Progress arrives as
/// `update_downloading` / `update_installed` / `update_error` events.
void installUpdate() => RustLib.instance.api.crateApiNullchatInstallUpdate();

/// The version waiting to be installed, empty when there is none.
String offeredUpdate() => RustLib.instance.api.crateApiNullchatOfferedUpdate();

/// This build's version, for the UI.
String appVersion() => RustLib.instance.api.crateApiNullchatAppVersion();

/// Tell the transport where the shipped binaries live.
///
/// Android refuses to execute anything outside the APK's native library folder,
/// so `tor` travels as `libtor.so` there and only the Java side knows the path.
/// Desktop builds find their binaries next to the executable and never call this.
void setNativeDir({required String path}) =>
    RustLib.instance.api.crateApiNullchatSetNativeDir(path: path);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UmbraApp>>
abstract class UmbraApp implements RustOpaqueInterface {
  /// Add a contact from a pasted `umbra1:` invite. Returns the parsed contact.
  ContactView addContact({required String inviteCode, required BigInt now});

  /// Add a contact to a group and push the new roster to everyone.
  GroupView addGroupMember({
    required String groupIdHex,
    required String contactHex,
  });

  void addMessage({
    required String contactHex,
    required bool outgoing,
    required BigInt sentAt,
    required String body,
  });

  /// Whether this account signs in automatically.
  bool autologinEnabled();

  /// Turn a duress passphrase off again. Needs the passphrase itself, since
  /// that is the only thing that can reach its rows.
  String clearDuressPassphrase({required String passphrase});

  /// Dial a stored contact over Tor and run the verified handshake.
  void connectPeer({required String contactHex});

  /// Does this contact have a post-quantum identity? Used by the UI to say so
  /// rather than implying protection a pre-1.9 contact does not have.
  bool contactIsPostQuantum({required String contactHex});

  /// Path to a contact's cached picture, or empty if we have none.
  String contactPicturePath({required String contactHex});

  /// Create a brand-new identity + encrypted store at `dir`, protected by
  /// `passphrase`.
  static UmbraApp create({
    required String dir,
    required String username,
    required String passphrase,
  }) => RustLib.instance.api.crateApiNullchatUmbraAppCreate(
    dir: dir,
    username: username,
    passphrase: passphrase,
  );

  /// Create a new account with its own identity and data directory.
  static UmbraApp createAccount({
    required String root,
    required String name,
    required String passphrase,
    required bool autologin,
  }) => RustLib.instance.api.crateApiNullchatUmbraAppCreateAccount(
    root: root,
    name: name,
    passphrase: passphrase,
    autologin: autologin,
  );

  /// Create a group from existing contacts. We are always a member, and the
  /// roster is pushed to everyone right away (it doubles as the invitation).
  GroupView createGroup({
    required String name,
    required List<String> memberHexes,
    required BigInt now,
  });

  /// Bridges the user pasted themselves, or empty when NullChat's own list is in
  /// use. Stored next to the account's Tor data, where the daemon reads it.
  String customBridges();

  /// Which duress passphrases this account has, as far as *we* can tell.
  ///
  /// Returns e.g. `["decoy"]`. This is a note we wrote for ourselves; a
  /// duress profile cannot see it, and neither can anyone without this
  /// passphrase.
  List<String> duressConfigured();

  /// Whether an identity already exists at `dir`.
  static bool exists({required String dir}) =>
      RustLib.instance.api.crateApiNullchatUmbraAppExists(dir: dir);

  /// Where finished incoming files are stored.
  String filesDir();

  /// Write a conversation into the decoy profile, so it is not suspiciously
  /// empty. Called from the real account, which is the only place that knows
  /// both passphrases.
  void fillDecoy({
    required String passphrase,
    required String contactName,
    required List<String> lines,
    required BigInt startAt,
  });

  /// Delete an account and everything it stored on this computer.
  static void forgetAccount({required String root, required String id}) =>
      RustLib.instance.api.crateApiNullchatUmbraAppForgetAccount(
        root: root,
        id: id,
      );

  /// Fetch a preview thumbnail, through Tor.
  ///
  /// The picker calls this instead of handing the URL to Flutter's image
  /// loader, which would fetch it over the clearnet and undo the whole point.
  Future<Uint8List> gifPreview({required String url});

  /// Search Tenor, over Tor, on a circuit of its own.
  ///
  /// The exit node that sees a search term is deliberately not the one
  /// carrying anything else this app does.
  Future<List<GifView>> gifSearch({required String query, required int limit});

  String identityHex();

  /// Leave a group: tell the others we are gone, then drop it locally with
  /// its whole history.
  void leaveGroup({required String groupIdHex});

  /// Accounts stored on this computer. Also migrates a pre-accounts install.
  static List<AccountView> listAccounts({required String root}) =>
      RustLib.instance.api.crateApiNullchatUmbraAppListAccounts(root: root);

  List<ContactView> listContacts();

  List<GroupMessageView> listGroupMessages({
    required String groupIdHex,
    required int limit,
  });

  List<GroupView> listGroups();

  List<MessageView> listMessages({
    required String contactHex,
    required int limit,
  });

  /// Everything one person has sent us, in the 1:1 thread and in groups.
  List<SearchHitView> messagesFromContact({
    required String contactHex,
    required int limit,
  });

  /// A shareable `umbra1:` invite carrying our identity, username and live
  /// onion address. Empty until the onion service is up.
  String myInvite();

  /// Our onion address, or empty while the network is still starting.
  String myOnion();

  /// Our profile picture bytes (empty when none is set).
  Uint8List myPicture();

  /// Open an existing identity at `dir` with `passphrase`.
  static UmbraApp open({required String dir, required String passphrase}) =>
      RustLib.instance.api.crateApiNullchatUmbraAppOpen(
        dir: dir,
        passphrase: passphrase,
      );

  /// Unlock an account with its passphrase, optionally remembering it.
  static UmbraApp openAccount({
    required String root,
    required String id,
    required String passphrase,
    required bool remember,
  }) => RustLib.instance.api.crateApiNullchatUmbraAppOpenAccount(
    root: root,
    id: id,
    passphrase: passphrase,
    remember: remember,
  );

  /// Unlock an account whose passphrase this computer remembers.
  static UmbraApp openAccountAuto({required String root, required String id}) =>
      RustLib.instance.api.crateApiNullchatUmbraAppOpenAccountAuto(
        root: root,
        id: id,
      );

  /// How many messages are still waiting for their peer.
  int pendingMessages();

  /// Give a contact the name you know them by.
  void renameContact({required String contactHex, required String name});

  /// Rename a group. The new name travels with the roster, so everyone sees
  /// it (a group has no owner — see `docs/THREAT_MODEL.md`).
  GroupView renameGroup({required String groupIdHex, required String name});

  /// Throw away Tor's cached directory data and start the network again.
  ///
  /// The identity and the onion address are kept — only what Tor can fetch
  /// again is deleted. This is the manual version of the repair the app
  /// already tries by itself when a bootstrap stalls.
  Stream<NetEvent> repairTor();

  /// The 60 digits this contact and I must both see, in groups of five.
  ///
  /// Empty when we have no such contact. Both sides compute it from the same
  /// two identity keys, so reading it aloud over a channel an attacker would
  /// have to control *as well* is what rules out a swapped invite.
  String safetyNumber({required String contactHex});

  /// Search every conversation for text. Both kinds of message are covered;
  /// newest first.
  List<SearchHitView> searchMessages({
    required String query,
    required int limit,
  });

  /// Send a file to a connected contact: read it, split it into chunks and
  /// push each one through the encrypted session. Progress arrives as events.
  void sendFile({required String contactHex, required String path});

  /// Send a GIF to a contact.
  ///
  /// **We** download it and push the bytes through the encrypted file
  /// channel. The recipient's device never contacts Tenor — sending a link
  /// instead would hand their IP address and the time to Google, which is the
  /// one thing this whole design exists to prevent.
  void sendGif({
    required String contactHex,
    required String gifUrl,
    required String description,
  });

  /// Send a group message: stored locally once, then fanned out over each
  /// member's own 1:1 session.
  void sendGroupMessage({
    required String groupIdHex,
    required String text,
    required BigInt now,
  });

  /// Store a message and send it. If the contact is not reachable it waits in
  /// the encrypted outbox and goes out by itself once they appear — closing
  /// the app does not lose it.
  void sendOverNetwork({
    required String contactHex,
    required String text,
    required BigInt now,
  });

  /// Turn auto sign-in on (needs the passphrase) or off for this account.
  void setAutologin({required String passphrase, required bool enabled});

  /// Keep a contact in the address book (or drop them from it).
  void setContactSaved({required String contactHex, required bool saved});

  /// Accept a waiting conversation (1), or block the contact (2). Blocking
  /// also drops whatever they still have queued with us.
  void setContactStatus({required String contactHex, required int status});

  /// Replace (or, with empty text, drop) the user's own bridge lines. Takes
  /// effect the next time Tor starts.
  void setCustomBridges({required String text});

  /// Add a second passphrase to this account.
  ///
  /// `kind` is `"decoy"` (its own separate history) or `"wipe"` (destroys
  /// everything it cannot read, then behaves like a new account). Both are
  /// optional and independent.
  ///
  /// The new passphrase gets its own identity and its own rows in the same
  /// file. Nothing records that it exists except a note sealed under *this*
  /// passphrase, so the file itself never says how many it answers to.
  void setDuressPassphrase({required String kind, required String passphrase});

  /// Set our profile picture (raw image bytes, stored encrypted) and push it
  /// to everyone we are connected to.
  void setMyPicture({required List<int> bytes});

  /// Record that the user compared the number and it matched (or take it
  /// back). Nothing in the protocol may call this — only a person can.
  void setVerified({required String contactHex, required bool verified});

  /// Start the Tor node: bootstrap (directly, falling back to bridges when
  /// the network blocks Tor), host our onion service, and accept incoming
  /// peers. Returns immediately — all progress arrives as [`NetEvent`]s.
  Stream<NetEvent> startNetwork();

  String userCode();

  String username();
}

/// One local account, as shown in the account picker.
class AccountView {
  final String id;
  final String name;

  /// Signs in without asking for the passphrase.
  final bool autologin;

  const AccountView({
    required this.id,
    required this.name,
    required this.autologin,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ autologin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          autologin == other.autologin;
}

/// A contact, flattened for the UI.
class ContactView {
  final String identityHex;
  final String userCode;
  final String displayName;
  final String onion;
  final BigInt addedAt;

  /// 0 = waiting for a decision, 1 = accepted, 2 = blocked.
  final int status;

  /// Kept in the address book.
  final bool saved;

  /// The user compared safety numbers with them and said it matched.
  final bool verified;

  const ContactView({
    required this.identityHex,
    required this.userCode,
    required this.displayName,
    required this.onion,
    required this.addedAt,
    required this.status,
    required this.saved,
    required this.verified,
  });

  @override
  int get hashCode =>
      identityHex.hashCode ^
      userCode.hashCode ^
      displayName.hashCode ^
      onion.hashCode ^
      addedAt.hashCode ^
      status.hashCode ^
      saved.hashCode ^
      verified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactView &&
          runtimeType == other.runtimeType &&
          identityHex == other.identityHex &&
          userCode == other.userCode &&
          displayName == other.displayName &&
          onion == other.onion &&
          addedAt == other.addedAt &&
          status == other.status &&
          saved == other.saved &&
          verified == other.verified;
}

/// One GIF search result, flattened for the picker.
class GifView {
  final String previewUrl;
  final String gifUrl;
  final int width;
  final int height;
  final String description;

  const GifView({
    required this.previewUrl,
    required this.gifUrl,
    required this.width,
    required this.height,
    required this.description,
  });

  @override
  int get hashCode =>
      previewUrl.hashCode ^
      gifUrl.hashCode ^
      width.hashCode ^
      height.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GifView &&
          runtimeType == other.runtimeType &&
          previewUrl == other.previewUrl &&
          gifUrl == other.gifUrl &&
          width == other.width &&
          height == other.height &&
          description == other.description;
}

/// One member of a group, flattened for the UI.
class GroupMemberView {
  final String identityHex;
  final String displayName;
  final String onion;

  const GroupMemberView({
    required this.identityHex,
    required this.displayName,
    required this.onion,
  });

  @override
  int get hashCode =>
      identityHex.hashCode ^ displayName.hashCode ^ onion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberView &&
          runtimeType == other.runtimeType &&
          identityHex == other.identityHex &&
          displayName == other.displayName &&
          onion == other.onion;
}

/// A message in a group, flattened for the UI.
class GroupMessageView {
  final String senderHex;

  /// Name from the roster, so the UI can label who wrote it.
  final String senderName;
  final bool outgoing;
  final BigInt sentAt;
  final String body;

  const GroupMessageView({
    required this.senderHex,
    required this.senderName,
    required this.outgoing,
    required this.sentAt,
    required this.body,
  });

  @override
  int get hashCode =>
      senderHex.hashCode ^
      senderName.hashCode ^
      outgoing.hashCode ^
      sentAt.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMessageView &&
          runtimeType == other.runtimeType &&
          senderHex == other.senderHex &&
          senderName == other.senderName &&
          outgoing == other.outgoing &&
          sentAt == other.sentAt &&
          body == other.body;
}

/// A group conversation, flattened for the UI.
class GroupView {
  final String idHex;
  final String name;
  final int version;
  final BigInt createdAt;
  final List<GroupMemberView> members;

  const GroupView({
    required this.idHex,
    required this.name,
    required this.version,
    required this.createdAt,
    required this.members,
  });

  @override
  int get hashCode =>
      idHex.hashCode ^
      name.hashCode ^
      version.hashCode ^
      createdAt.hashCode ^
      members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupView &&
          runtimeType == other.runtimeType &&
          idHex == other.idHex &&
          name == other.name &&
          version == other.version &&
          createdAt == other.createdAt &&
          members == other.members;
}

/// A stored message, flattened for the UI.
class MessageView {
  final bool outgoing;
  final BigInt sentAt;
  final String body;

  /// 0 = still waiting for the peer, 1 = handed over, 2 = confirmed by them.
  final int state;

  const MessageView({
    required this.outgoing,
    required this.sentAt,
    required this.body,
    required this.state,
  });

  @override
  int get hashCode =>
      outgoing.hashCode ^ sentAt.hashCode ^ body.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageView &&
          runtimeType == other.runtimeType &&
          outgoing == other.outgoing &&
          sentAt == other.sentAt &&
          body == other.body &&
          state == other.state;
}

/// An event from the network layer, pushed to the UI.
///
/// `kind` is one of:
/// `"status"` (bootstrapping / connecting…), `"onion"` (our address is ready),
/// `"connected"` / `"disconnected"` (peer session), `"message"` (incoming text),
/// `"error"`.
class NetEvent {
  final String kind;
  final String data;
  final String peerHex;

  const NetEvent({
    required this.kind,
    required this.data,
    required this.peerHex,
  });

  @override
  int get hashCode => kind.hashCode ^ data.hashCode ^ peerHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          data == other.data &&
          peerHex == other.peerHex;
}

/// A message found by search, or one a contact sent us.
class SearchHitView {
  /// Who wrote it (or, in a 1:1 thread, the other party).
  final String peerHex;

  /// Empty for a direct message, otherwise the group it was written in.
  final String groupHex;
  final bool outgoing;
  final BigInt sentAt;
  final String body;

  const SearchHitView({
    required this.peerHex,
    required this.groupHex,
    required this.outgoing,
    required this.sentAt,
    required this.body,
  });

  @override
  int get hashCode =>
      peerHex.hashCode ^
      groupHex.hashCode ^
      outgoing.hashCode ^
      sentAt.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHitView &&
          runtimeType == other.runtimeType &&
          peerHex == other.peerHex &&
          groupHex == other.groupHex &&
          outgoing == other.outgoing &&
          sentAt == other.sentAt &&
          body == other.body;
}
