// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `broadcast_group_info`, `dial_once`, `emit`, `flush_pending`, `handle_payload`, `hex`, `identity_pubkey`, `install_dir`, `log_line`, `now_secs`, `queue_message`, `remember_group_routes`, `rt`, `send_or_queue`, `send_profile`, `spawn_keepalive`, `spawn_updater`, `unhex16`, `unhex`, `view_of`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inner`, `Pending`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// This build's version, for the UI.
String appVersion() => RustLib.instance.api.crateApiUmbraAppVersion();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UmbraApp>>
abstract class UmbraApp implements RustOpaqueInterface {
  /// Add a contact from a pasted `umbra1:` invite. Returns the parsed contact.
  ContactView addContact({required String inviteCode, required BigInt now});

  /// Add a contact to a group and push the new roster to everyone.
  GroupView addGroupMember({
    required String groupIdHex,
    required String contactHex,
  });

  void addMessage({
    required String contactHex,
    required bool outgoing,
    required BigInt sentAt,
    required String body,
  });

  /// Whether this account signs in automatically.
  bool autologinEnabled();

  /// Dial a stored contact over Tor and run the verified handshake.
  void connectPeer({required String contactHex});

  /// Path to a contact's cached picture, or empty if we have none.
  String contactPicturePath({required String contactHex});

  /// Create a brand-new identity + encrypted store at `dir`, protected by
  /// `passphrase`.
  static UmbraApp create({
    required String dir,
    required String username,
    required String passphrase,
  }) => RustLib.instance.api.crateApiUmbraUmbraAppCreate(
    dir: dir,
    username: username,
    passphrase: passphrase,
  );

  /// Create a new account with its own identity and data directory.
  static UmbraApp createAccount({
    required String root,
    required String name,
    required String passphrase,
    required bool autologin,
  }) => RustLib.instance.api.crateApiUmbraUmbraAppCreateAccount(
    root: root,
    name: name,
    passphrase: passphrase,
    autologin: autologin,
  );

  /// Create a group from existing contacts. We are always a member, and the
  /// roster is pushed to everyone right away (it doubles as the invitation).
  GroupView createGroup({
    required String name,
    required List<String> memberHexes,
    required BigInt now,
  });

  /// Whether an identity already exists at `dir`.
  static bool exists({required String dir}) =>
      RustLib.instance.api.crateApiUmbraUmbraAppExists(dir: dir);

  /// Where finished incoming files are stored.
  String filesDir();

  /// Delete an account and everything it stored on this computer.
  static void forgetAccount({required String root, required String id}) =>
      RustLib.instance.api.crateApiUmbraUmbraAppForgetAccount(
        root: root,
        id: id,
      );

  String identityHex();

  /// Leave a group: tell the others we are gone, then drop it locally with
  /// its whole history.
  void leaveGroup({required String groupIdHex});

  /// Accounts stored on this computer. Also migrates a pre-accounts install.
  static List<AccountView> listAccounts({required String root}) =>
      RustLib.instance.api.crateApiUmbraUmbraAppListAccounts(root: root);

  List<ContactView> listContacts();

  List<GroupMessageView> listGroupMessages({
    required String groupIdHex,
    required int limit,
  });

  List<GroupView> listGroups();

  List<MessageView> listMessages({
    required String contactHex,
    required int limit,
  });

  /// A shareable `umbra1:` invite carrying our identity, username and live
  /// onion address. Empty until the onion service is up.
  String myInvite();

  /// Our onion address, or empty while the network is still starting.
  String myOnion();

  /// Our profile picture bytes (empty when none is set).
  Uint8List myPicture();

  /// Open an existing identity at `dir` with `passphrase`.
  static UmbraApp open({required String dir, required String passphrase}) =>
      RustLib.instance.api.crateApiUmbraUmbraAppOpen(
        dir: dir,
        passphrase: passphrase,
      );

  /// Unlock an account with its passphrase, optionally remembering it.
  static UmbraApp openAccount({
    required String root,
    required String id,
    required String passphrase,
    required bool remember,
  }) => RustLib.instance.api.crateApiUmbraUmbraAppOpenAccount(
    root: root,
    id: id,
    passphrase: passphrase,
    remember: remember,
  );

  /// Unlock an account whose passphrase this computer remembers.
  static UmbraApp openAccountAuto({required String root, required String id}) =>
      RustLib.instance.api.crateApiUmbraUmbraAppOpenAccountAuto(
        root: root,
        id: id,
      );

  /// Send a file to a connected contact: read it, split it into chunks and
  /// push each one through the encrypted session. Progress arrives as events.
  void sendFile({required String contactHex, required String path});

  /// Send a group message: stored locally once, then fanned out over each
  /// member's own 1:1 session.
  void sendGroupMessage({
    required String groupIdHex,
    required String text,
    required BigInt now,
  });

  /// Send a message to the currently connected peer.
  void sendOverNetwork({required String contactHex, required String text});

  /// Turn auto sign-in on (needs the passphrase) or off for this account.
  void setAutologin({required String passphrase, required bool enabled});

  /// Set our profile picture (raw image bytes, stored encrypted) and push it
  /// to everyone we are connected to.
  void setMyPicture({required List<int> bytes});

  /// Start the Tor node: bootstrap (through bundled obfs4 bridges when
  /// present), host our onion service, and accept incoming peers. Returns
  /// immediately — all progress arrives as [`NetEvent`]s on the stream.
  Stream<NetEvent> startNetwork();

  String userCode();

  String username();
}

/// One local account, as shown in the account picker.
class AccountView {
  final String id;
  final String name;

  /// Signs in without asking for the passphrase.
  final bool autologin;

  const AccountView({
    required this.id,
    required this.name,
    required this.autologin,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ autologin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          autologin == other.autologin;
}

/// A contact, flattened for the UI.
class ContactView {
  final String identityHex;
  final String userCode;
  final String displayName;
  final String onion;
  final BigInt addedAt;

  const ContactView({
    required this.identityHex,
    required this.userCode,
    required this.displayName,
    required this.onion,
    required this.addedAt,
  });

  @override
  int get hashCode =>
      identityHex.hashCode ^
      userCode.hashCode ^
      displayName.hashCode ^
      onion.hashCode ^
      addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactView &&
          runtimeType == other.runtimeType &&
          identityHex == other.identityHex &&
          userCode == other.userCode &&
          displayName == other.displayName &&
          onion == other.onion &&
          addedAt == other.addedAt;
}

/// One member of a group, flattened for the UI.
class GroupMemberView {
  final String identityHex;
  final String displayName;
  final String onion;

  const GroupMemberView({
    required this.identityHex,
    required this.displayName,
    required this.onion,
  });

  @override
  int get hashCode =>
      identityHex.hashCode ^ displayName.hashCode ^ onion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberView &&
          runtimeType == other.runtimeType &&
          identityHex == other.identityHex &&
          displayName == other.displayName &&
          onion == other.onion;
}

/// A message in a group, flattened for the UI.
class GroupMessageView {
  final String senderHex;

  /// Name from the roster, so the UI can label who wrote it.
  final String senderName;
  final bool outgoing;
  final BigInt sentAt;
  final String body;

  const GroupMessageView({
    required this.senderHex,
    required this.senderName,
    required this.outgoing,
    required this.sentAt,
    required this.body,
  });

  @override
  int get hashCode =>
      senderHex.hashCode ^
      senderName.hashCode ^
      outgoing.hashCode ^
      sentAt.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMessageView &&
          runtimeType == other.runtimeType &&
          senderHex == other.senderHex &&
          senderName == other.senderName &&
          outgoing == other.outgoing &&
          sentAt == other.sentAt &&
          body == other.body;
}

/// A group conversation, flattened for the UI.
class GroupView {
  final String idHex;
  final String name;
  final int version;
  final BigInt createdAt;
  final List<GroupMemberView> members;

  const GroupView({
    required this.idHex,
    required this.name,
    required this.version,
    required this.createdAt,
    required this.members,
  });

  @override
  int get hashCode =>
      idHex.hashCode ^
      name.hashCode ^
      version.hashCode ^
      createdAt.hashCode ^
      members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupView &&
          runtimeType == other.runtimeType &&
          idHex == other.idHex &&
          name == other.name &&
          version == other.version &&
          createdAt == other.createdAt &&
          members == other.members;
}

/// A stored message, flattened for the UI.
class MessageView {
  final bool outgoing;
  final BigInt sentAt;
  final String body;

  const MessageView({
    required this.outgoing,
    required this.sentAt,
    required this.body,
  });

  @override
  int get hashCode => outgoing.hashCode ^ sentAt.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageView &&
          runtimeType == other.runtimeType &&
          outgoing == other.outgoing &&
          sentAt == other.sentAt &&
          body == other.body;
}

/// An event from the network layer, pushed to the UI.
///
/// `kind` is one of:
/// `"status"` (bootstrapping / connecting…), `"onion"` (our address is ready),
/// `"connected"` / `"disconnected"` (peer session), `"message"` (incoming text),
/// `"error"`.
class NetEvent {
  final String kind;
  final String data;
  final String peerHex;

  const NetEvent({
    required this.kind,
    required this.data,
    required this.peerHex,
  });

  @override
  int get hashCode => kind.hashCode ^ data.hashCode ^ peerHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          data == other.data &&
          peerHex == other.peerHex;
}
